stages:
- build

variables:
  BUILD_VERSION: "0.3.1"
  NUGET_APIKEY: "0F2DB634-4E83-4659-8068-EF552DDC4072"
  NUGET_SERVER: "http://172.20.5.15/nugetServer/"

before_script:
- set

develop_build_job:
  stage: build
  only:
  - master
  - develop
  script:
  - if %CI_BUILD_REF_NAME% == master  set BUILD_TARGET=
  - if %CI_BUILD_REF_NAME% == develop set BUILD_TARGET=-BETA
  - c:\Multi-Runner\nuget.exe restore
  - '"c:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe" /p:Configuration=Release /p:Platform="Any CPU" VWParty.Infra.Messaging.sln'
  - c:\Multi-Runner\nuget.exe pack VWParty.Infra.Messaging\VWParty.Infra.Messaging.csproj -Properties Configuration=Release -Version %BUILD_VERSION%%BUILD_TARGET%
  - c:\Multi-Runner\nuget.exe push VWParty.Infra.Messaging.%BUILD_VERSION%%BUILD_TARGET%.nupkg -ApiKey %NUGET_APIKEY% -Source %NUGET_SERVER%


# script 都跟 develop_build_job 相同。只有調整 BUILD_VERSION 與對應的 branch
#master_build_job:
#  stage: build
#  only:
#  - master
#  script:
#  - c:\Multi-Runner\nuget.exe restore
#  - '"c:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe" /p:Configuration=Release /p:Platform="Any CPU" /p:VersionAssembly=%BUILD_VERSION% VWParty.Infra.Messaging.sln'
#  - c:\Multi-Runner\nuget.exe pack VWParty.Infra.Messaging\VWParty.Infra.Messaging.csproj -Properties Configuration=Release -Version %BUILD_VERSION%
#  - c:\Multi-Runner\nuget.exe push VWParty.Infra.Messaging.%BUILD_VERSION%.nupkg -ApiKey %NUGET_APIKEY% -Source %NUGET_SERVER%